### ISSUE TITLE
Choisir un composant d'arbre

### ISSUE THREAD

**Issue by mdartic** [sodriihm/sodriihm-front#2]
Le choix de Quasar avait été décidé à l'époque pour le composant d'arbre.

Avec la création de ce nouveau repo, et pour ne pas regretter plus tard la reprise du code, il faudrait voir ce qui existe comme composants d'arbre sur les différents frameworks / bibliothèques.

**Comment by SimonMellerin** [comment]
Après quelques recherches, voici la liste que j'ai retenue: 

- Quasar (composant actuellement utilisé) : 
  - Lien : https://quasar.dev/vue-components/tree
  - \+ : Déjà implémenté
  - \- : il faut embarquer Quasar
- Primevue : 
  - Lien : https://primevue.org/tree
  - \+ : Complet et simple d'utilisation
  - \- : il faut embarquer Primevue
- Vue3 Router Tree : 
  - Lien :  https://boussadjra.github.io/vue3-router-tree
  - \+ : indépendant de tout framework ou bibliothèque de composant
  - \- : semble abandonné
- Solution maison : 
  - \+ : maitrise complète
  - \- : temps de développement
- Simple tree view
  - Lien : 
    - https://github.com/petrbroz/simple-treeview
    - demo: https://unpkg.com/simple-treeview@0.0.9/examples/bootstrap.html
    - \+ : Vanilla js
    - \- : semble abandonné, fonctionne étrange à coup de callback

Conclusion (vu ce matin ave l'équipe) :

- l'équipe actuelle est familière de Quasar
- certains composants déjà développés à l'aide de Quasar pourront être récupérés

Il semble pertinent de rester sur Quasar. Il faudrait cependant vérifier que l'on arrive à faire ce qu'on veux avec cf https://github.com/sodriihm/sodriihm-front/issues/3

On avisera donc à l'issue des tests avec Quasar

**Comment by mdartic** [comment]
le gagnant est PrimeVue cf #3
