### ISSUE TITLE
Choix d'un framework front (quasar / ... ?)

### ISSUE THREAD

**Issue by mdartic** [sodriihm/sodriihm-front#3]
Suite au daily de ce jour, se pose la question de reprendre le framework Quasar, car les composants d'arbre "ailleurs" ne sont pas forcément mieux.

Ce ticket est ici pour tester la mise en place d'un projet avec Quasar CLI, et sans Quasar CLI (juste en mode "picorage" de composants).

Des difficultés de configuration ont été remontées par l'équipe en place, et il faudrait essayer de créer des stories et des tests unitaires pour tacler ces difficultés.
Cela permettrait de confirmer le choix de Quasar.

**edit du 4 Septembre**

Au delà de Quasar, et avec les retours de Simon sur l'accessibilité et l'approche Material, il faudrait trancher entre Quasar et PrimeVue.

J'ajoute quelques liens pour que chacun puisse se documenter et avoir son opinion.

**Comment by mdartic** [comment]
**côté accessibilité**

_quasar_

- https://github.com/quasarframework/quasar/discussions/12441
- https://github.com/quasarframework/quasar/issues/11889

_primevue_

- https://primevue.org/introduction/#accessibility
- https://primevue.org/guides/accessibility (bon, ça reste des principes généraux, rien à voir avec primevue)
- https://primevue.org/inputtext/#accessibility : là, c'est un composant basique d'input, mais est détaillé les possibilités côté accessibilité
- https://github.com/primefaces/primevue/issues/2822 , une des issues pour améliorer un composant complexe sur l'accessibilité, l'autocomplete

**côté composants**

_treeselect_

- quasar https://quasar.dev/vue-components/tree#selection-vs-ticking-expansion
- prime https://primevue.org/treeselect/

_tree_

- quasar https://quasar.dev/vue-components/tree
- prime https://primevue.org/tree/

_treetable_ (pas sûr qu'on en ait besoin, je le mets quand même)

- quasar ?
- primevue https://primevue.org/treetable/

_autocomplete_

- quasar https://quasar.dev/vue-components/select#filtering-and-autocomplete
- prime https://primevue.org/autocomplete/

_dialog_

- quasar https://quasar.dev/vue-components/dialog
- primevue https://primevue.org/dialog/

_stepper_ (utilisé dans les maquettes)

- quasar https://quasar.dev/vue-components/stepper
- primevue https://primevue.org/stepper/

_validation de formulaire_

- https://vee-validate.logaretm.com/v4/examples/ui-libraries
- les deux libs fonctionnent avec, c'est une bonne chose !

_tailwindcss_

- ça, c'est mes habitudes de petit vieux https://tailwindcss.com/
- quasar https://github.com/quasarframework/quasar/issues/6775 / https://stackoverflow.com/questions/70034269/how-to-use-tailwind-css-with-quasar-framework
- primevue https://tailwind.primevue.org/ bon, c'est intégré et c'est plutôt chouette

**Comment by mathieu-massaviol** [comment]
J'ai pu parcourir la documentation de PrimeVue que je trouve très claire et je ne vois (de mon côté) pas de frein à son utilisation. Au niveau de l'arbre il propose les mêmes fonctionnalités que j'ai pu utiliser avec l'arbre Quasar (lazy loading et selection multiple).

PrimeVue a en effet l'air d'être plus avancé que Quasar niveau accessibilité.

**Comment by EdLou16** [comment]
Je confirme @mathieu-massaviol que la documentation de PrimeVue est très claire et de mon côté également, Je ne vois pas non plus de frein à son utilisation. 
Et en la parcourant, je me rends compte que niveau accessibilité PrimeVue est bien au dessus de Quasar. PrimeVue est plus avancé sur ce point.
Pour ma part les deux composants qui me semble essentiels et que j'ai utilisé avec Quasar ( l'arbre avec routing et le select avec les options emit-value/map-options (https://quasar.dev/vue-components/select#affecting-model)) sont présents dans PrimeVue et offre les mêmes fonctionnalités : https://primevue.org/tree/#template, https://primevue.org/select/#template.

**Comment by mdartic** [comment]
On valide donc le choix de PrimeVue, merci pour vos retours.
